# Generated by Django 4.1.4 on 2022-12-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verified_puppers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='original_img',
            field=models.ImageField(null=True, upload_to='dog_images'),
        ),
    ]
