# Generated by Django 4.1.4 on 2022-12-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verified_puppers', '0003_alter_dog_original_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='modified_img',
            field=models.ImageField(null=True, upload_to='verified_puppers/images'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='original_img',
            field=models.ImageField(null=True, upload_to='verified_puppers/images'),
        ),
    ]
